
name: studio-nuxt-build
run-name: studio nuxt build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: vepic/vepic-main

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Identify package manager
        id: pkgman
        run: |
          cd vepic/vepic-main
          cache=$( [ -f "pnpm-lock.yaml" ] && echo "pnpm" || ([ -f "package-lock.json" ] && echo "npm" || ([ -f "yarn.lock" ] && echo "yarn" || echo "")) )
          package_manager=$( [ ! -z "$cache" ] && echo "$cache" || echo "npm" )
          echo "cache=$cache" >> $GITHUB_OUTPUT
          echo "package_manager=$package_manager" >> $GITHUB_OUTPUT

      - name: Install pnpm
        if: ${{ steps.pkgman.outputs.package_manager == 'pnpm' }}
        uses: pnpm/action-setup@v4
        id: pnpm-install

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: ${{ steps.pkgman.outputs.cache }}

      - name: Install dependencies
        run: ${{ steps.pkgman.outputs.package_manager }} install

      - name: Generate build
        run: ${{ steps.pkgman.outputs.package_manager }} run build
        env:
          NITRO_PRESET: github_pages
          NUXT_CONTENT_PREVIEW_API: https://api.nuxt.studio

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: vepic/vepic-main/.output/public
